CREATE TABLE contador_registro (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero NUMBER NOT NULL,
  registrado_en TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Opcional: crear usuario y grant (ejemplo)
-- CREATE USER contador_user IDENTIFIED BY strong_password;
-- GRANT CONNECT, RESOURCE TO contador_user;
-- GRANT CREATE TABLE TO contador_user;
COMMIT;